language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
deploy:
  provider: cargo
  token: $CRATESIO_TOKEN
  on:
    tags: true
